### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by yuqiang923** [uzh-rpg/rpg_vid2e#1]
I build esim-py with "python setup.py install",  but I got the error blew when import esim-py
undefined symbol: _ZN2cv12VideoCapture4readERNS_3MatE
 
When "ldd -r esim_py.cpython-37m-x86_64-linux-gnu.so", many undefined symbol error.

**Comment by yuqiang923** [comment]
Fixed. First, I change OpenCV to 2.4. Second, I add "pybind11::embed" in target_link_libraries.

**Comment by PhilippeCb** [comment]
I build esim-py with `pip install .` I don't have an error but when trying `python tests/test.py` I get 
`ImportError: /home/philippe/anaconda3/envs/vid2e/lib/python3.7/site-packages/esim_py.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathEPNS_6system10error_codeE`
It looks similar to this issue but I can create an other issue if needed

**Comment by ahadviger** [comment]
Try changing the last line of CMakeLists.txt to

`target_link_libraries(esim_py PRIVATE libesim ${OpenCV_LIBS} Boost::filesystem Boost::system Eigen3::Eigen pybind11::embed)`

This fixed the same error for me!

**Comment by PhilippeCb** [comment]
Thank you, it worked

**Comment by magehrig** [comment]
[Fixed](https://github.com/uzh-rpg/rpg_vid2e/commit/199eaf67a1da3dd19cceea683a8585023dd826ba), thanks!

**Comment by YixinYang-00** [comment]
> I build esim-py with `pip install .` I don't have an error but when trying `python tests/test.py` I get
> `ImportError: /home/philippe/anaconda3/envs/vid2e/lib/python3.7/site-packages/esim_py.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathEPNS_6system10error_codeE`
> It looks similar to this issue but I can create an other issue if needed

I have a same issue, but the change of the last line of CMakeList.txt can't fix it.
Besides, I add a `cmake_policy(SET CMP0057 NEW)` at the second line of CMakelist.
