### ISSUE TITLE
About implementation of segmentation

### ISSUE THREAD

**Issue by wl082013** [uzh-rpg/rpg_vid2e#10]
Hi, Thanks for this amazing work.
I am kind of interested in the application to segmentation, but I did not see the code of segmentation.
Could you please share it? 
About EST, did you apply event representation to evsegnet in TensorFlow? 
Or you change to PyTorch ?
Thanks for your help.

**Comment by magehrig** [comment]
Thanks for you interest!

- We are not planning to open source the segmentation code
- We first modified the open source version of EV-Segnet but at some point decided to re-implemented it in Pytorch
