### ISSUE TITLE
 errors in installing rpg_vid2e

### ISSUE THREAD

**Issue by yeyeleijun** [uzh-rpg/rpg_vid2e#14]
Hi all,
     It raises errors (attached [error.txt](https://github.com/uzh-rpg/rpg_vid2e/files/5611446/error.txt) file) when I run `pip install `. I did follow every step of your instructions at Github, and there is no errors before `pip install .`  Could you please help me figure it out? Thank you very much. I am looking forward to your reply.

**Comment by magehrig** [comment]
Please switch to gcc 6.0 or later to rule out that it is a C++ standard issue.

**Comment by yeyeleijun** [comment]
My gcc version is 6.3.0.
`(vid2e) [yelj@head01 esim_py]$ gcc -v`
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/6.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --disable-multilib
Thread model: posix
gcc version 6.3.0 (GCC)`

And it seems that I tried to install with `python setup.py install`, so there is still something left after I run `pip unistall vid2e`.
`(vid2e) [yelj@head01 esim_py]$ pip uninstall esim_py`
`Found existing installation: esim-py 0.0.1
Can't uninstall 'esim-py'. No files were found to uninstall.
`

And the `python setup.py install` command also raises some errors (attched [error2.txt](https://github.com/uzh-rpg/rpg_vid2e/files/5612161/error2.txt)).

**Comment by magehrig** [comment]
Hmm that is strange because in your error message it says that gcc is looking in `/usr/include/c++/4.8.2`. I.e. it looks like either you are using gcc 4.8.2 or the search path is wrong.
Taken from your text file:
```
[ 25%] Building CXX object CMakeFiles/libesim.dir/src/esim.cpp.o
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
```

**Comment by yeyeleijun** [comment]
I have changed my default gcc search path by adding `export C_INCLUDE_PATH=/usr/local/include/c++/8.2.0:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/usr/local/include/c++/8.2.0:$CPLUS_INCLUDE_PATH
` to the`.bashrc` file. 

And now some new errors raises([error3.txt](https://github.com/uzh-rpg/rpg_vid2e/files/5613622/error3.txt))

Both the gcc 6.3.0 and gcc 8.2.0 get the similar errors. Is there anyting wrong with my gcc or something else?

**Comment by magehrig** [comment]
Could you show me the output of `conda env`?

**Comment by yeyeleijun** [comment]
The output of `conda list` is [output.txt](https://github.com/uzh-rpg/rpg_vid2e/files/5623657/output.txt)

**Comment by magehrig** [comment]
Ok that seems to be fine. I searched for a possible solution but could only found an [issue on another repository](https://github.com/uwsampa/accept/issues/51) suggesting that is a problem with Clang. However, I don't have a solution for this.

**Comment by yeyeleijun** [comment]
Ok, thank you all the same for your help. : )
