### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by YU-Zhiyang** [uzh-rpg/rpg_vid2e#15]
when I run python tests/plot_virtual_events.py an error raise:
Traceback (most recent call last):
  File "tests/plot_virtual_events.py", line 56, in <module>
    events = esim.generateFromFolder(image_folder, timestamps_file)
MemoryError: std::bad_alloc

**Comment by pgksgp** [comment]
I too have this issue. Please check
