### ISSUE TITLE
Upsampling video leads to flashing

### ISSUE THREAD

**Issue by studywolf** [uzh-rpg/rpg_vid2e#18]
Hello, 

When I run the code on the video provided there's a flashing effect, is this expected? 

https://user-images.githubusercontent.com/2473097/113879513-95d45880-9788-11eb-87bc-9a11ecdf0fda.mp4

**Comment by studywolf** [comment]
here's a gif version, which is hopefully viewable 

![ezgif-3-fe48eeefad93](https://user-images.githubusercontent.com/2473097/113879675-c4523380-9788-11eb-8781-fb4aabe6b5d3.gif)

**Comment by ezius07** [comment]
I had this issue as well with pytorch 1.8.1, it is not an expected outcome. 
We solved it by using by downgrading pytorch to version 1.3.1, the updated version when the repo was published.

**Comment by studywolf** [comment]
awesome, thanks!

**Comment by studywolf** [comment]
Oop, i'm still getting the flashing after downgrading to torch==1.3.1, could I get your pip list output to compare other package versions?

**Comment by ezius07** [comment]
Sure!
[requirements.txt](https://github.com/uzh-rpg/rpg_vid2e/files/6326308/requirements.txt)
 I am attaching it as a requirements file

**Comment by studywolf** [comment]
thanks so much! this resolved the issue for me
