### ISSUE TITLE
Installing esim_py failed

### ISSUE THREAD

**Issue by anindya2001** [uzh-rpg/rpg_vid2e#21]
Thanks for your pathbreaking work!
While trying to install esim_py on google colaboratory, they are giving the following output. As suggested, I've run the following lines of code to adapt the CUDA toolkit version:

cuda_version=10.1
!conda create -y -n vid2e python=3.7
!conda activate vid2e
!conda install -y pytorch torchvision cudatoolkit=$cuda_version -c pytorch
!conda install -y -c conda-forge opencv tqdm scikit-video eigen boost boost-cpp pybind11

Can you suggest a possible solution to solve this issue? Thanks in advance.
![image](https://user-images.githubusercontent.com/42895181/118720362-22be0780-b847-11eb-89d6-aa39580226f9.png)

**Comment by danielgehrig18** [comment]
Hi, unfortunately, from the error message I cannot tell where the problem lies. Can you share with me more details of what failed in the installation?

**Comment by anindya2001** [comment]
HI, I am sharing the colab notebook [link](https://www.cityscapes-dataset.com/dataset-overview/) here. You can see the details from here. Thanks in advance.

**Comment by danielgehrig18** [comment]
The link you posted brings me to the city scapes website. Is this correct?

**Comment by anindya2001** [comment]
Extremely sorry for that. I had changed that link thereafter, please check. Thanks.

**Comment by danielgehrig18** [comment]
Thanks, it says that you can check the logs to find the error. I am not
sure how this is done. Do you know where the logs are stored?

**Comment by anindya2001** [comment]
Sure. You can run the whole notebook once and find the logs under the 'Runtime' section, as shown in this figure. Again, thanks for looking into the notebook.
![image](https://user-images.githubusercontent.com/42895181/118840505-17b9b480-b8e5-11eb-9b0b-3a6ca61ce0ee.png)

**Comment by danielgehrig18** [comment]
Can you post them here?

**Comment by danielgehrig18** [comment]
This issue has been solved by the most recent commit. You can now pull the binaries precompiled.

**Comment by ashantanu** [comment]
Hi @anindya2001 , were you able to run this on colab?
