### ISSUE TITLE
I can run on gtx1080ti, but can't run on rtx 2080ti or rtx 3090, I always meet the error below. 

### ISSUE THREAD

**Issue by DachunKai** [uzh-rpg/rpg_vid2e#41]
```python
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
And my docker environment is: cuda10.2, cudnn7, pytorch1.6, python3.7.

All gpus, include gtx1080ti, rtx2080ti, or rtx3090 driver are all >= 470.  I can only run the docker image successfully on gtx1080ti with the same code.

I don't know the reason.

**Comment by magehrig** [comment]
Hi @DachunKai 

Could you give it a try by installing Pytorch from source?
