### ISSUE TITLE
ModuleNotFoundError: No module named 'esim_torch'

### ISSUE THREAD

**Issue by mlchen666** [uzh-rpg/rpg_vid2e#44]
I successfully compiled and installed the _esim_torch_ package with the commands:
```shell
cd rpg_vid2e/esim_torch
pip install .
```
However, I got the following errors while trying `python test/test.py`:
> Traceback (most recent call last):
File "/xxx/rpg_vid2e/esim_torch/test/test.py", line 7, in <module>
import esim_torch
ModuleNotFoundError: No module named 'esim_torch'

**Comment by MinglinChen94** [comment]
I fixed this with the following two steps:
Step 1: move the directory _rpg_vid2e/esim_torch/src/esim_torch_ by the following commands:
```shell
mv -r rpg_vid2e/esim_torch/src/esim_torch rpg_vid2e/esim_torch/
```
Step 2: modify the file _rpg_vid2e/esim_torch/setup.py_ as:
```python
from setuptools import setup
from torch.utils.cpp_extension import BuildExtension, CUDAExtension

setup(
    name='esim_torch',
    packages=['esim_torch'], # package_dir={'':'src'},
    ext_modules=[
        CUDAExtension(name='esim_cuda',
                      sources=[
                      'esim_torch/esim_cuda_kernel.cu', # 'src/esim_torch/esim_cuda_kernel.cu',
                      ],
                     # extra_compile_args={
                     #'cxx': ['-g'],
                     #'nvcc': ['-arch=sm_60', '-O3', '-use_fast_math']
                     #}
                     )
    ],
    cmdclass={
        'build_ext': BuildExtension
    })

```

**Comment by gintautas12358** [comment]
thanks mlchen666, you saved me a day or two

**Comment by EMJian** [comment]
Thanks a lot. It works for me。

**Comment by hjyanzju** [comment]
step3: in  the file  esim_torch/scripts/generate_events.py:
change:
` import esim_torch`
to:
`from esim_torch import esim_torch  `

**Comment by danielgehrig18** [comment]
This should be fixed with the latest commit, it was an issue with the setup.py
