### ISSUE TITLE
Missing the last image of the original images

### ISSUE THREAD

**Issue by EMJian** [uzh-rpg/rpg_vid2e#49]
In the first step, upsampling operation, the last image of the original images is not stored on the upsampled images.
For example/seq2, there are 9 images in the original images. 1 image is interpolated into the original images between two consecutive images. But the upsampled results only have 16 images due to the lack of the last image of the original images. This results in a missing section of the events stream. Its timestamps also confirm this matter.
It is the same for example/seq0.
![1](https://user-images.githubusercontent.com/58971148/167813212-27aedef8-4f46-44b2-89cb-cfabcff88e66.png)

**Comment by danielgehrig18** [comment]
good point, if you add 

timestamps.append(t1)
total_frames.append(I1)

after the for loop this could resolve the issue. If yes please make a PR. Thanks!

**Comment by EMJian** [comment]
OK.
It could resolve this issue.
I also make a pull request.
