### ISSUE TITLE
Question about generating events from stamped image sequence

### ISSUE THREAD

**Issue by yujeong-star** [uzh-rpg/rpg_vid2e#6]
Hi, 
I have a question about the function "generateFromStampedImageSequence" in esim_py.
```
# generate events from list of images and timestamps 
events_list_of_images = esim.generateFromStampedImageSequence(
    list_of_image_files,   # list of absolute paths to images
    list_of_timestamps     # list of timestamps in ascending order
)
```

I successfully installed esim_py and could generate events with "generateFromStampedImageSequence".
But when I put image list and timestamp of length 2, it produces empty list of events.
For the detail explanation, if list_of_image_files = [img1, img2], and list_of_timestamps is the .txt file with two timestamps (e.g. 0.000000000 and 0.001865671), events_list_of_images produces [].

It works fine when the length of image sequence is higher than 2.
Is there any reason for that or am I the only one having this issue?

Thanks in advance!

**Comment by danielgehrig18** [comment]
Hi yujeong-star, I belive it might have to do with the fact that the change between the two images is too small (smaller than the contrast threshold). Have you tried using a smaller contrast threshold? Otherwise it is also possible that your two images are identical. Let me know.

**Comment by yujeong-star** [comment]
Hi again,
I changed the contrast threshold to 0 following your comment but events_list_of_images is still empty. Also two images are not identical..

The number of events are different when I run "generateFromStampedImageSequence" with [img1, img2, img3, img4] and [img2, img3, img4]. But with [img1, img2], nothing happens.

I was just curious why this happens. Thanks for your reply!

**Comment by danielgehrig18** [comment]
I would not set the threshold to 0 since this would theoretically generate
an infinite number of events. Can you maybe set up a test case to check
this behavior with your two images?

**Comment by yujeong-star** [comment]
```
import esim_py

esim = esim_py.EventSimulator(0.05, 0.05, 0, 0.001, True)

### first case: three images
list_of_image_files = ['/data/images/images/image_00016.png',
                       '/data/images/images/image_00017.png',
                       '/data/images/images/image_00018.png' ]
list_of_timestamps = [0.000000000, 0.001865671, 0.003731343]

events_list_of_images = esim.generateFromStampedImageSequence(
                    list_of_image_files, list_of_timestamps)

print(events_list_of_images.shape) ### output: (3566, 4)

### second case: two images
list_of_image_files = ['/data/images/images/image_00017.png',
                       '/data/images/images/image_00018.png' ]
list_of_timestamps = [0.000000000, 0.001865671]

events_list_of_images = esim.generateFromStampedImageSequence(
                    list_of_image_files, list_of_timestamps)

print(events_list_of_images.shape) ### output: (0, 4)
```
This is the test code. 
I set the threshold to 0.05 instead of 0, and I used the given images in this github. 
Thanks!

**Comment by danielgehrig18** [comment]
Thanks alot, can you also share the images you used?

**Comment by yujeong-star** [comment]
The image URLs are 
https://github.com/uzh-rpg/rpg_vid2e/blob/master/esim_py/tests/data/images/images/image_00016.png
https://github.com/uzh-rpg/rpg_vid2e/blob/master/esim_py/tests/data/images/images/image_00017.png
https://github.com/uzh-rpg/rpg_vid2e/blob/master/esim_py/tests/data/images/images/image_00018.png
They are already in the esim_py code. Thanks!

**Comment by DenisDiachkov** [comment]
Hi, I met the same problem. Did you find a solution?

**Comment by yujeong-star** [comment]
@DenisDiachkov Not yet :'(
@danielgehrig18 How did you generate synthetic events between the frames while training? 
I tried to train my network using the synthetic events between two consecutive frames, but are there any other ways to use it? maybe like processing multiple images at once? 
Thank you for sharing python binding code of esim. :)

**Comment by danielgehrig18** [comment]
Hi guys,

I managed to find the bug which caused this behavior. It should be fixed now. You can have a look. 
@yujeong-star now I think it should be possible to use two frames during trainig. However, I think that multiple frames should be better (in our case we used ~50) since in most cases two images is not enough.

**Comment by yujeong-star** [comment]
Hi, thanks a lot for fixing the problem!
However I faced a new problem while re-installing.
I first uninstalled the esim_py, redownloaded this github code, reinstalled esim_py, and following error occurred.

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import esim_py
ImportError: /home/yujeong/anaconda3/envs/python3.6/lib/python3.6/site-packages/esim_py.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost6system15system_categoryEv

I tried many things like changing contents in CMakeLists.txt, but it has the same error..
Thanks in advance!

**Comment by danielgehrig18** [comment]
Hey yujeong-star, did you make sure to install the correct conda packages? Please compare the output of your conda environment with the output below (call `conda list -e`)
```bash
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
boost=1.70.0=py37h9de70de_1
boost-cpp=1.70.0=ha2d47e9_1
bzip2=1.0.8=h516909a_2
ca-certificates=2020.6.20=hecda079_0
cairo=1.16.0=h18b612c_1001
certifi=2020.6.20=py37hc8dfbb8_0
eigen=3.3.7=hc9558a2_1001
esim-py=0.0.1=pypi_0
ffmpeg=4.0=hcdf2ecd_0
fontconfig=2.13.1=he4413a7_1000
freeglut=3.0.0=hf484d3e_1005
freetype=2.10.2=he06d7ca_0
glib=2.65.0=h3eb4bd4_0
graphite2=1.3.13=he1b5a44_1001
harfbuzz=1.8.8=hffaf4a1_0
hdf5=1.10.2=hc401514_3
icu=58.2=hf484d3e_1000
jasper=2.0.14=habb8e15_1
jpeg=9d=h516909a_0
ld_impl_linux-64=2.33.1=h53a641e_7
libblas=3.8.0=14_openblas
libcblas=3.8.0=14_openblas
libedit=3.1.20191231=h7b6447c_0
libffi=3.3=he6710b0_1
libgcc-ng=9.1.0=hdf63c60_0
libgfortran=3.0.0=1
libgfortran-ng=7.5.0=hdf63c60_6
libglu=9.0.0=he1b5a44_1001
liblapack=3.8.0=14_openblas
libopenblas=0.3.7=h5ec1e0e_6
libopencv=3.4.2=hb342d67_1
libopus=1.3.1=h7b6447c_0
libpng=1.6.37=hed695b0_1
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.1.0=hc7e4089_6
libuuid=2.32.1=h14c3975_1000
libvpx=1.7.0=h439df22_0
libwebp-base=1.1.0=h516909a_3
libxcb=1.13=h14c3975_1002
libxml2=2.9.10=he19cac6_1
lz4-c=1.9.2=he1b5a44_1
ncurses=6.2=he6710b0_1
numpy=1.18.5=py37h8960a57_0
opencv=3.4.2=py37h6fd60c2_1
openssl=1.1.1g=h516909a_0
pcre=8.44=he1b5a44_0
pip=20.1.1=py37_1
pixman=0.38.0=h516909a_1003
pthread-stubs=0.4=h14c3975_1001
py-opencv=3.4.2=py37hb342d67_1
pybind11=2.5.0=py37h99015e2_0
python=3.7.7=hcff3b4d_5
python_abi=3.7=1_cp37m
readline=8.0=h7b6447c_0
scikit-video=1.1.11=pyh24bf2e0_0
scipy=1.5.0=py37ha3d9a3c_0
setuptools=47.3.1=py37_0
sqlite=3.32.3=h62c20be_0
tk=8.6.10=hbc83047_0
tqdm=4.47.0=pyh9f0ad1d_0
wheel=0.34.2=py37_0
xorg-fixesproto=5.0=h14c3975_1002
xorg-inputproto=2.3.2=h14c3975_1002
xorg-kbproto=1.0.7=h14c3975_1002
xorg-libice=1.0.10=h516909a_0
xorg-libsm=1.2.3=h84519dc_1000
xorg-libx11=1.6.9=h516909a_0
xorg-libxau=1.0.9=h14c3975_0
xorg-libxdmcp=1.1.3=h516909a_0
xorg-libxext=1.3.4=h516909a_0
xorg-libxfixes=5.0.3=h516909a_1004
xorg-libxi=1.7.10=h516909a_0
xorg-libxrender=0.9.10=h516909a_1002
xorg-renderproto=0.11.1=h14c3975_1002
xorg-xextproto=7.3.0=h14c3975_1002
xorg-xproto=7.0.31=h14c3975_1007
xz=5.2.5=h7b6447c_0
zlib=1.2.11=h7b6447c_3
zstd=1.4.4=h6597ccf_3
```

**Comment by yujeong-star** [comment]
My output of conda environment was almost same as yours.
I solved it by removing "Eigen3::Eigen" in target_link_libraries and adding the line "add_definitions ( {$Eigen3_DEFINITIONS})".
Thanks always!!! :)
