### ISSUE TITLE
esim_py and esim_torch are not working on Windows 10 nor Ubuntu

### ISSUE THREAD

**Issue by HamadYA** [uzh-rpg/rpg_vid2e#70]
Hi,

I followed the same steps in READMe and I could not install esim_py and esim_torch. I tried both Windows 10 nor Ubuntu and still getting errors.

Kindly advise.

**Comment by chinmay0301** [comment]
I encountered similar problem. I made some progress on the installation though, by building opencv from source, and installing eigen3 and boost independently in my environment. 

https://www.geeksforgeeks.org/how-to-install-opencv-in-c-on-linux/ 
https://www.devmanuals.net/install/ubuntu/ubuntu-20-04-focal-fossa/installing-libeigen3-dev-on-ubuntu20-04.html
https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu
