### ISSUE TITLE
simulation error in ngspice Fatal error: BSIM3v32: mosfet cmosn, model m3: Effective channel length <= 0

### ISSUE THREAD

**Issue by gouravjha7** [uzh-rpg/rpg_vid2e#9]
I was trying to simulate my circuit on ngspice which i have been made on kicad. Now is show me error like this: 

Fatal error: BSIM3v32: mosfet cmosn, model m3: Effective channel length <= 0
doAnalyses: no such parameter on this device

run simulation(s) aborted

**Comment by magehrig** [comment]
This error does not occur in the code of this repository. Please open an issue at ngspice instead.
